apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: network
spec:
  selector:
    matchLabels:
      app: network
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: network
    spec:
      containers:
      - image: amouat/network-utils
        name: network
        command:
        - sleep
        - 1d
      tolerations:
      - effect: NoSchedule
        key: robobeerun.com/dedicated
        operator: Exists
      - effect: NoSchedule
        key: dedicated
        operator: Exists
      - effect: NoSchedule
        key: node.alpha.kubernetes.io/ismaster
        operator: Exists
