apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: test
  name: network-test
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image: amouat/network-utils
        name: network
        command:
        - sleep
        - 1d
      tolerations:
      - effect: NoSchedule
        key: robobeerun.com/dedicated
        operator: Exists
      - effect: NoSchedule
        key: dedicated
        operator: Exists
      - effect: NoSchedule
        key: node.alpha.kubernetes.io/ismaster
        operator: Exists
  updateStrategy:
    type: RollingUpdate
